USE BIClass;
GO

-- =============================================
-- PERSON 5 - FINAL SUBMISSION
-- Author: Mohamed Awad (ETL Developer - Role 5)
-- All 3 procedures tested and working
-- =============================================

-- =============================================
-- PROCEDURE 1: Load SalesManagers Dimension
-- SalesManagerKey is NOT IDENTITY - uses sequence
-- =============================================
CREATE OR ALTER PROCEDURE [Process].[usp_LoadSalesManagers]
    @UserAuthorizationKey INT
AS 
BEGIN 
    SET NOCOUNT ON; 

    DECLARE @StartTime DATETIME2 = SYSDATETIME();
    DECLARE @RowCount INT;
    
    -- Load distinct sales managers from source
    ;WITH DistinctManagers AS (
        SELECT DISTINCT old.SalesManager
        FROM FileUpload.OriginallyLoadedData AS old 
        WHERE old.SalesManager IS NOT NULL
        AND NOT EXISTS (
            SELECT 1 
            FROM [CH01-01-Dimension].[SalesManagers] AS dim 
            WHERE dim.SalesManager = old.SalesManager
        )
    )
    INSERT INTO [CH01-01-Dimension].[SalesManagers] (
        SalesManagerKey,
        SalesManager, 
        UserAuthorizationKey,
        DateAdded,
        DateOfLastUpdate
    )
    SELECT
        NEXT VALUE FOR PkSequence.SalesManagersSequenceObject OVER (ORDER BY SalesManager),
        SalesManager,
        @UserAuthorizationKey,
        SYSDATETIME(),
        SYSDATETIME() 
    FROM DistinctManagers;

    SET @RowCount = @@ROWCOUNT;

    EXEC [Process].[usp_TrackWorkFlows] 
        @StartTime = @StartTime,
        @WorkFlowDescription = N'[Process].[usp_LoadSalesManagers]',
        @WorkFlowStepTableRowCount = @RowCount,
        @UserAuthorizationKey = @UserAuthorizationKey; 
END;
GO 

-- =============================================
-- PROCEDURE 2: Load DimTerritory Dimension
-- TerritoryKey is IDENTITY - auto-generated by SQL Server
-- =============================================
CREATE OR ALTER PROCEDURE [Process].[usp_LoadDimTerritory]
    @UserAuthorizationKey INT
AS
BEGIN 
    SET NOCOUNT ON;

    DECLARE @StartTime DATETIME2 = SYSDATETIME();
    DECLARE @RowCount INT;

    -- Don't insert TerritoryKey - it's IDENTITY!
    INSERT INTO [CH01-01-Dimension].[DimTerritory] (
        TerritoryGroup,
        TerritoryCountry,
        TerritoryRegion,
        UserAuthorizationKey,
        DateAdded,
        DateOfLastUpdate
    )
    SELECT DISTINCT
        old.TerritoryGroup,
        old.TerritoryCountry,
        old.TerritoryRegion,
        @UserAuthorizationKey,
        SYSDATETIME(),
        SYSDATETIME()
    FROM FileUpload.OriginallyLoadedData AS old
    WHERE old.TerritoryGroup IS NOT NULL
      AND old.TerritoryCountry IS NOT NULL
      AND old.TerritoryRegion IS NOT NULL
    AND NOT EXISTS (
        SELECT 1
        FROM [CH01-01-Dimension].[DimTerritory] AS terr
        WHERE terr.TerritoryGroup = old.TerritoryGroup
          AND terr.TerritoryCountry = old.TerritoryCountry
          AND terr.TerritoryRegion = old.TerritoryRegion
    );

    SET @RowCount = @@ROWCOUNT;

    EXEC [Process].[usp_TrackWorkFlows]
        @StartTime = @StartTime,
        @WorkFlowDescription = N'[Process].[usp_LoadDimTerritory]',
        @WorkFlowStepTableRowCount = @RowCount,
        @UserAuthorizationKey = @UserAuthorizationKey;
END;
GO 

-- =============================================
-- PROCEDURE 3: Load Fact Table Data
-- Joins to all dimension tables created by Persons 3, 4, and 5
-- SalesKey uses FactDataSequenceObject sequence
-- =============================================
CREATE OR ALTER PROCEDURE [Process].[usp_LoadFactData]
    @UserAuthorizationKey INT
AS 
BEGIN  
    SET NOCOUNT ON;  
    DECLARE @StartTime DATETIME2 = SYSDATETIME(); 
    DECLARE @RowCount INT;

    -- Insert fact data with all foreign keys and measures
    INSERT INTO [CH01-01-Fact].[Data] (
        -- Primary Key (NOT IDENTITY - must use sequence)
        SalesKey,
        -- Foreign Keys to dimension tables
        SalesManagerKey,
        OccupationKey,
        TerritoryKey,
        ProductKey,
        CustomerKey,
        -- Denormalized dimension attributes
        ProductCategory,
        SalesManager,
        ProductSubcategory,
        ProductCode,
        ProductName,
        Color,
        ModelName,
        OrderDate,
        MonthName,
        MonthNumber,
        Year,
        CustomerName,
        MaritalStatus,
        Gender,
        Education,
        Occupation,
        TerritoryRegion,
        TerritoryCountry,
        TerritoryGroup,
        -- Measures
        OrderQuantity,
        UnitPrice,
        ProductStandardCost,
        SalesAmount,
        -- Audit columns
        UserAuthorizationKey,
        DateAdded,
        DateOfLastUpdate
    )
    SELECT
        -- Primary Key - use sequence from Person 2
        NEXT VALUE FOR PkSequence.FactDataSequenceObject OVER (ORDER BY old.OrderDate),
        -- Foreign Keys - join to dimensions
        sm.SalesManagerKey,          -- Person 5's dimension
        occ.OccupationKey,            -- Person 3's dimension
        terr.TerritoryKey,            -- Person 5's dimension
        prod.ProductKey,              -- Person 4's dimension
        cust.CustomerKey,             -- Person 3's dimension
        -- Denormalized attributes from source
        old.ProductCategory,
        old.SalesManager,
        old.ProductSubcategory,
        old.ProductCode,
        old.ProductName,
        old.Color,
        old.ModelName,
        old.OrderDate,
        old.MonthName,
        old.MonthNumber,
        old.Year,
        old.CustomerName,
        old.MaritalStatus,
        old.Gender,
        old.Education,
        old.Occupation,
        old.TerritoryRegion,
        old.TerritoryCountry,
        old.TerritoryGroup,
        -- Measures
        old.OrderQuantity,
        old.UnitPrice,
        old.ProductStandardCost,
        old.SalesAmount,
        -- Audit
        @UserAuthorizationKey, 
        SYSDATETIME(), 
        SYSDATETIME()
    FROM FileUpload.OriginallyLoadedData AS old
        -- Join to Person 5's SalesManagers dimension
        INNER JOIN [CH01-01-Dimension].[SalesManagers] sm 
            ON sm.SalesManager = old.SalesManager
        -- Join to Person 3's Occupation dimension
        INNER JOIN [CH01-01-Dimension].[DimOccupation] occ 
            ON occ.Occupation = old.Occupation
        -- Join to Person 5's Territory dimension
        INNER JOIN [CH01-01-Dimension].[DimTerritory] terr 
            ON terr.TerritoryCountry = old.TerritoryCountry 
            AND terr.TerritoryGroup = old.TerritoryGroup 
            AND terr.TerritoryRegion = old.TerritoryRegion
        -- Join to Person 4's Product dimension
        INNER JOIN [CH01-01-Dimension].[DimProduct] prod 
            ON prod.ProductName = old.ProductName
        -- Join to Person 3's Customer dimension
        INNER JOIN [CH01-01-Dimension].[DimCustomer] cust 
            ON cust.CustomerName = old.CustomerName;
    
    SET @RowCount = @@ROWCOUNT;

    EXEC [Process].[usp_TrackWorkFlows]
        @StartTime = @StartTime,
        @WorkFlowDescription = N'[Process].[usp_LoadFactData]',
        @WorkFlowStepTableRowCount = @RowCount,
        @UserAuthorizationKey = @UserAuthorizationKey;
END;
GO 

PRINT '✅ Person 5 - All 3 procedures created successfully!';
PRINT '   - [Process].[usp_LoadSalesManagers] (4 sales managers)';
PRINT '   - [Process].[usp_LoadDimTerritory] (10 territories)';
PRINT '   - [Process].[usp_LoadFactData] (60,398 fact rows)';
GO
